version: "3"

services:
  # frontend:
  #   container_name: frontend_blog
  #   build: ./front-end
  #   volumes:
  #     - ./front-end/src:/app-frontend/src
  #   ports:
  #     - 5173:5173
  #   platform: linux/x86_64
  #   networks:
  #     - blogs-api-networks
  #   working_dir: /app-frontend
  #   depends_on:
  #     - backend


  backend:
    container_name: backend-blog
    build: ./back-end
    # volumes:
    #   - ./front-end/src:/app-backend/src
    platform: linux/x86_64
    working_dir: /app-backend
    ports:
      - 3002:3001
    networks:
      - blogs-api-networks
    depends_on:
      - db

  db:
    image: mysql:8.0.29
    container_name: blogs-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=BLOGS
    networks:
      - blogs-api-networks
    ports:
      - 3306:3306

networks:
  blogs-api-networks:
    name: blogs-api-networks